"""
img_to_ascii.py - Convert album cover images to colored pixel data for TUI rendering.

Usage:
    python img_to_ascii.py --image path/to/cover.jpg --album "ARIRANG"
    python img_to_ascii.py --image path/to/cover.jpg --album "Proof" --width 38 --height 19

This will:
1. Resize the image to the given dimensions (default 38x19 for ~square terminal cells)
2. Extract RGB pixel data
3. Save to src/album_art.json
4. Regenerate src/album_art.rs (Rust static arrays)

Requirements:
    pip install Pillow
"""

import argparse
import json
import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

JSON_PATH = Path("src/album_art.json")
RUST_PATH = Path("src/album_art.rs")


def image_to_pixels(image_path: str, width: int, height: int) -> list[list[tuple[int, int, int]]]:
    """Resize image and extract RGB pixels as a 2D grid."""
    img = Image.open(image_path).convert("RGB")
    # Crop to square first so it doesn't stretch
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    img = img.crop((left, top, left + side, top + side))
    img = img.resize((width, height), Image.LANCZOS)

    rows = []
    for y in range(height):
        row = []
        for x in range(width):
            r, g, b = img.getpixel((x, y))
            row.append([r, g, b])
        rows.append(row)
    return rows


def save_json(album: str, width: int, height: int, rows: list) -> dict:
    """Load existing JSON data, update the given album, and save."""
    data = {}
    if JSON_PATH.exists():
        with open(JSON_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)

    data[album] = {"width": width, "height": height, "pixels": rows}

    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f)

    return data


def rust_const_name(album: str) -> str:
    """Convert album name to a safe Rust const identifier."""
    name = album.upper()
    for ch in " '-.:,/\\'\"()[]{}":
        name = name.replace(ch, "_")
    # Collapse multiple underscores
    while "__" in name:
        name = name.replace("__", "_")
    return name.strip("_")


def generate_rust(data: dict) -> str:
    """Generate the full Rust source file with static pixel arrays."""
    lines = [
        "// Auto-generated by img_to_ascii.py — DO NOT EDIT MANUALLY",
        "// Re-run img_to_ascii.py to update album art.",
        "",
        "/// Returns (width, height, flat_pixels) for a given album name.",
        "/// Each pixel is (r, g, b).",
        "pub fn get_album_pixels(album: &str) -> Option<(usize, usize, &'static [(u8, u8, u8)])> {",
        "    match album {",
    ]

    for album_name in data:
        const = rust_const_name(album_name)
        entry = data[album_name]
        w, h = entry["width"], entry["height"]
        lines.append(f"        \"{album_name}\" => Some(({w}, {h}, &{const}_PIXELS)),")

    lines += [
        "        _ => None,",
        "    }",
        "}",
        "",
    ]

    for album_name, entry in data.items():
        const = rust_const_name(album_name)
        flat = [p for row in entry["pixels"] for p in row]
        total = len(flat)
        lines.append(f"pub static {const}_PIXELS: [(u8, u8, u8); {total}] = [")
        # Write 8 pixels per line for readability
        for i in range(0, total, 8):
            chunk = flat[i : i + 8]
            row_str = ", ".join(f"({p[0]},{p[1]},{p[2]})" for p in chunk)
            lines.append(f"    {row_str},")
        lines.append("];")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Convert album art image to TUI pixel data.")
    parser.add_argument("--image", required=True, help="Path to the album cover image")
    parser.add_argument("--album", required=True, help='Album name (e.g. "ARIRANG")')
    parser.add_argument(
        "--width",
        type=int,
        default=38,
        help="Width in terminal columns (default: 38)",
    )
    parser.add_argument(
        "--height",
        type=int,
        default=76,
        help="Pixel height (default: 76 = 2x width, rendered as 38 terminal rows using ▀ half-blocks)",
    )
    args = parser.parse_args()

    if not os.path.exists(args.image):
        print(f"ERROR: Image not found: {args.image}")
        sys.exit(1)

    print(f"Processing '{args.album}' from {args.image} at {args.width}x{args.height}...")
    rows = image_to_pixels(args.image, args.width, args.height)

    print(f"Saving pixel data to {JSON_PATH}...")
    data = save_json(args.album, args.width, args.height, rows)

    print(f"Generating {RUST_PATH}...")
    rust_src = generate_rust(data)
    with open(RUST_PATH, "w", encoding="utf-8") as f:
        f.write(rust_src)

    print(f"Done! {len(data)} album(s) in {RUST_PATH}.")
    print()
    print("Pixels stored at double height for half-block rendering.")
    print("Each pair of pixel rows = 1 terminal row -> square art.")
    print()
    print("Rebuild with: cargo run")


if __name__ == "__main__":
    main()
